apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-bot
  template:
    metadata:
      labels:
        app: js-bot
    spec:
      containers:
        - name: js-bot
          image: js-bot:latest
          imagePullPolicy: Never
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: BOT_TOKEN
