apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-bot
  template:
    metadata:
      labels:
        app: js-bot
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: js-bot
          image: ghcr.io/saba-chkhikvadze/js-bot:latest
          imagePullPolicy: Always
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: BOT_TOKEN
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: SECRET_KEY
            - name: ADMIN_PASSWORD_HASH
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: ADMIN_PASSWORD_HASH
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: REDIS_URL
          envFrom:
            - configMapRef:
                name: discord-bot-config