name: Deploy to k3s

on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t js-bot:latest .

      - name: Import image into k3s
        run: |
          docker save js-bot:latest | sudo k3s ctr images import -
      
      - name: Deploy to k3s
        run: |
          kubectl rollout restart deployment/js-bot
          kubectl rollout status deployment/js-bot --timeout=120s  